# Generated by Django 3.2.4 on 2021-06-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210626_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ManageInfo',
        ),
    ]
