# Generated by Django 3.2.4 on 2021-06-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_shippingaddress_manageinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyitem',
            name='qty',
        ),
    ]
