# Generated by Django 3.2.4 on 2021-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_applyitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='manageinfo',
            name='shippingPrice',
        ),
    ]
