# Generated by Django 3.2.4 on 2021-06-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210627_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='isPaid',
            field=models.BooleanField(default=True),
        ),
    ]
