# Generated by Django 3.2.4 on 2021-06-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
