# Generated by Django 3.2.4 on 2021-06-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='paidAt',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
