# Generated by Django 3.2.4 on 2021-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_apply_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
