# Generated by Django 3.2.4 on 2021-06-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_review_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageinfo',
            old_name='address',
            new_name='message',
        ),
    ]
