# Generated by Django 3.2.4 on 2021-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_address_manageinfo_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cartname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='cartnumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='securitycode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
