# Generated by Django 3.2.4 on 2021-06-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210630_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='paidAt',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
