# Generated by Django 3.2.4 on 2021-06-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210701_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='isNotDelivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apply',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
