# Generated by Django 3.2.4 on 2021-07-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210701_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.post'),
        ),
    ]
