# Generated by Django 3.2.4 on 2021-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_apply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
